### ISSUE TITLE
Issues setting downstream

### ISSUE THREAD

**Issue by kramos** [RobertNorthard/adop-pipeline-builder#4]
1. The cartridge collection loader expects it to be called downstream_folder.  See:
https://github.com/kramos/adop-platform-management/blob/master/projects/jobs/jobs.groovy#L342

2. (Minor) the downstream for production is being set to "Production_Pipeline", it should be unset
https://gist.githubusercontent.com/anonymous/a05ca0e651052deb016823347d5b0498/raw

3. The downstream for an integration pipeline is not being set, it should be the downstream integration pipeline name or PROD
https://gist.githubusercontent.com/anonymous/a05ca0e651052deb016823347d5b0498/raw

4. The "Production_Pipeline" is being called "PROD" whereas "Production_Pipeline"  is a both better name and what CI pipelines off the Prod node are expecting (see ADOP_Flyway_Cartridge)
https://gist.githubusercontent.com/anonymous/a05ca0e651052deb016823347d5b0498/raw

5. The downstream for CI pipelines off an integration pipeline is being set to "Application_Pipeline", it needs to be set to the name of the downstream Integration pipeline e.g. Integration1 in 
https://gist.githubusercontent.com/anonymous/a05ca0e651052deb016823347d5b0498/raw
OR to "Production_Pipeline".

Happy to demo.

**Comment by RobertNorthard** [comment]
Thanks @kramos.

See [PR#2](https://github.com/RobertNorthard/adop-pipeline-builder/pull/6)

1. Looks like I was programming to a different JSON file. Renamed downstream to downstream_folder.
2. This can be unset.
3. Unable to reproduce. 
4. PROD renamed to Production_Pipeline
5. This was a conditional bug in which int upstream was being ignored.

In general the code needs tidying up. I've raised an [issue#7](https://github.com/RobertNorthard/adop-pipeline-builder/issues/7) for this.

I'm also thinking for a future enhancement we generate the diagram from an existing "cartridge collection". This would not be to tricky with the current schema and provides some persistence.

**Comment by kramos** [comment]
Great, I tested it end to end.
